apiVersion: v1
kind: Service

metadata:
  name: employee-portal-svc
  namespace: employee-portal-ns

spec:
  selector:
    app: employee-portal

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
